# SPDX-FileCopyrightText: 2021 Kaelan Thijs Fouwels <kaelan.thijs@fouwels.com>
#
# SPDX-License-Identifier: MIT

services:
  driver:
    image: ghcr.io/fouwels/tel:dev
    build:
      dockerfile: Dockerfile
      context: "./"
    environment: 
        DRIVER: mqtt
        OPC: opc.tcp://localhost:4840
        CONFIG_TAGLIST: /config/taglist.yml
        CONFIG_DRIVER: /config/driver.yml
    # Required for GOOSE/raw sockets (only)
    # user: root
    network_mode: host
    # cap_add:
    #   - cap_net_admin
    configs: 
      - source: taglist
        target: /config/taglist.yml
      - source: driver
        target: /config/driver.yml

configs:
  taglist:
    file: config/taglist.yml
  driver:
    file: config/mqtt.yml
