# SPDX-FileCopyrightText: 2021 Kaelan Thijs Fouwels <kaelan.thijs@fouwels.com>
#
# SPDX-License-Identifier: MIT

services:
  mqtt:
    image: registry2.lagoni.co.uk/lagoni-engineering/tel:dev
    build:
      dockerfile: Dockerfile
      context: "./"
    environment: 
        CONFIG_TAGLIST: config/taglist.yml
        CONFIG_DRIVER: config/mqtt.yml
        OPC: opc.tcp://localhost:4840
        DRIVER: mqtt
    network_mode: host
    volumes: 
      - ./config:/config:ro
