# SPDX-FileCopyrightText: 2021 Kaelan Thijs Fouwels <kaelan.thijs@fouwels.com>
#
# SPDX-License-Identifier: MIT

meta:
  site: example
  comment: example tag list
modbus:
  mode: tcp
  target: localhost:5002
  scantime_ms: 100
  timeout_ms: 1000
  slave: 1
