# SPDX-FileCopyrightText: 2022 Kaelan Thijs Fouwels <kaelan.thijs@fouwels.com>
#
# SPDX-License-Identifier: MIT
meta:
  site: example
  comment: example goose device
goose:
  device:
    label: goose_1
    interface: eth2
    application_id: 0x0003
    gocb_reference: GTNETGSECTRL1/LLN0$GO$gcb01
    filter_mac: 01-0c-cd-01-01-af
    observer: false
  tags: []
