# SPDX-FileCopyrightText: 2021 Kaelan Thijs Fouwels <kaelan.thijs@fouwels.com>
#
# SPDX-License-Identifier: MIT
meta:
  site: example
  comment: example mqtt device
mqtt:
  device:
    label: mqtt_cloud
    target: tcps://telemetry.lagoni.co.uk:8883
    client_id: telemetry_site
    username: service
    token: 5069-ceb6-d88c-9e52-45c4-fb0c
    timeout_ms: 1000
    keepalive_ms: 1000
  tags:
    - name: VALVE_OPEN
      topic: scada/tags
    - name: VALVE_CLOSE
      topic: scada/tags
    - name: VALVE_LIMIT_A
      topic: scada/tags
    - name: VALVE_LIMIT_B
      topic: scada/tags
    - name: VALVE_FLOW_A
      topic: scada/tags
    - name: VALVE_FLOW_B
      topic: scada/tags
    - name: VALVE_FLOW_C
      topic: scada/tags
    - name: VALVE_PROPORTIONAL
      topic: scada/tags
