# SPDX-FileCopyrightText: 2021 Kaelan Thijs Fouwels <kaelan.thijs@fouwels.com>
#
# SPDX-License-Identifier: MIT

meta:
  site: example
  comment: example tag list
tags:
  - name: VALVE_OPEN
    namespace: TAGS
    description: Valve Open
    type: bool
    default_value: 0

  - name: VALVE_CLOSE
    namespace: TAGS
    description: Valve Close
    type: bool
    default_value: 0

  - name: VALVE_LIMIT_A
    namespace: TAGS
    description: Value Limit Switch A
    type: bool
    default_value: 0

  - name: VALVE_LIMIT_B
    namespace: TAGS
    description: Value Limit Switch B
    type: bool
    default_value: 0

  - name: VALVE_FLOW_A
    namespace: TAGS
    description: Valve Flow A
    type: uint16
    default_value: 0

  - name: VALVE_FLOW_B
    namespace: TAGS
    description: Valve Flow B
    type: uint16
    default_value: 0

  - name: VALVE_FLOW_C
    namespace: TAGS
    description: Valve Flow C
    type: uint16
    default_value: 0

  - name: VALVE_PROPORTIONAL
    namespace: TAGS
    description: Valve Proportional
    type: uint16
    default_value: 0

  - name: GTNETGSECTRL1/LLN0$GOOSE_outputs_1[0]
    namespace: GOOSE
    description: Unknown
    type: uint16
    default_value: 0
