# SPDX-FileCopyrightText: 2021 Kaelan Thijs Fouwels <kaelan.thijs@fouwels.com>
#
# SPDX-License-Identifier: MIT

meta:
  site: example
  comment: example tag list
tags:
  - name: VALVE_OPEN
    namespace: TAGS
    description: bool valve
    type: bool
    default_value: 1
    index: C.0

  - name: VALVE_CLOSED
    namespace: TAGS
    description: bool valve
    type: bool
    default_value: 0
    index: D.0

  - name: FLOW_A
    namespace: TAGS
    description: uint16 flow
    type: int16
    default_value: -325
    index: I.0

  - name: FLOW_B
    namespace: TAGS
    description: uint16 flow
    type: uint16
    default_value: 325
    index: I.0

  - name: FLOW_C
    namespace: TAGS
    description: uint16 flow
    type: int16
    default_value: -325
    index: H.0

  - name: FLOW_D
    namespace: TAGS
    description: uint16 flow
    type: uint16
    default_value: 325
    index: H.0
